### ISSUE TITLE
UI doesn't load properly in web browser. Happened in Safari, Google Chrome and Firefox 

### ISSUE THREAD

**Issue by mmgarcia** [armandleopold/graphexp-docker#2]
The UI looks like missing any library:

I tried to run inside of container and directly in a NGINX server but got the same result. 

Server settings.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/4342204/87294786-3d5e7c00-c4d2-11ea-9545-05feadff38a6.png">

<img width="955" alt="image" src="https://user-images.githubusercontent.com/4342204/87294899-6979fd00-c4d2-11ea-8c5a-315cf15e59d1.png">
<img width="958" alt="image" src="https://user-images.githubusercontent.com/4342204/87295003-8f9f9d00-c4d2-11ea-8e0d-a0a58766aea5.png">

**Comment by armandleopold** [comment]
Yes it was because of a unmanaged broken change from the sources that triggered the ci/cd pipeline that built the docker image on the latest tag which erased the correct image.

You can use the newly tagged docker image  : 0.8.1.2
https://hub.docker.com/repository/docker/aleopold/docker-graphexp

`docker pull aleopold/docker-graphexp:0.8.1.2`

Sorry for the inconvenience.
Regards.
